name: Publish

on:
  workflow_run:
    workflows:
      - CI
    types:
        - completed

jobs:
  publish-testpypi:
    name: Publish to TestPyPi
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/confuse-jsonschema

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        skip-existing: true

  publish-pypi:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    environment:
      name: pypi
      url: https://pypi.org/p/confuse-jsonschema

    permissions:
      id-token: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
